### ISSUE TITLE
Re-export xdr

### ISSUE THREAD

**Issue by liranco** [xetdata/nfsserve#13]
Hi,

I'm trying to implement an nfs server with a custom storage backend, and need to serialize some of the types defined (such as `fattr3`).
Is it possible to re-export the xdr module so its serialization functionality may be used externally?

Many thanks for this crate!
Liran

**Comment by ylow** [comment]
For sure. Does this suffice? https://github.com/xetdata/nfsserve/pull/14/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759

**Comment by liranco** [comment]
This works! Thanks :)
