### ISSUE TITLE
Windows NFS server port need to be 111

### ISSUE THREAD

**Issue by freshmanken** [xetdata/nfsserve#18]
Hi, does the demo work for Windows Server 2019? Tried the Windows Server 2019 version and also the Windows 10 Enterprise version but the mount command always returns
```
mount.exe -o anon,nolock,mtype=soft,fileaccess=6,casesensitive,lang=ansi,rsize=128,wsize=128,timeout=60,retry=2 \\127.0.0.1\\ X:

Network Error - 53
Type 'NET HELPMSG 53' for more information.
```
Where the HELPMSG shows "The network path was not found." I can confirm Client for NFS is installed and restarted. This is an amazing lib! Recently tried out ProjFS but it didn't meet the needs so am really anticipating on this (: 

Thanks in advance!

**Comment by freshmanken** [comment]
Figured out that it's due to the port. Seems like for Windows port 111 is the only port that works. Default 11111 or anything else won't get recognized due to portmapper?

**Comment by latot** [comment]
!! weird...

**Comment by ylow** [comment]
Yeah. It is possible windows does not support alternate ports for NFS. For some googling I could only find 1 question with no answer, but a comment indicating it might be impossible. https://serverfault.com/questions/935092/mount-nfs-share-in-windows-on-non-standard-port

**Comment by freshmanken** [comment]
Thanks, yeah there's no port option for `mount.exe` : https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mount. Tried `net use` or `New-PSDrive` too which lacks the same option and results the same...Seems like this will be the restriction for NFSv3 on Windows. Not sure if it will be more flexible with NFSv4 as it doesn't require portmapper anymore?

**Comment by ylow** [comment]
If mount.exe doesn't have the ability to specify an option... then I guess there wouldn't be a way to provide a port number even for NFSv4 either?

**Comment by freshmanken** [comment]
Yeah makes sense. Btw will there be any future plan to support dynamic port on Windows? If not I can close this thread up (: thanks for the replies

**Comment by ylow** [comment]
I think even if we support it, I don't think windows can mount it. So I think this will be a wontfix.
