### ISSUE TITLE
Case Insensitivty

### ISSUE THREAD

**Issue by freshmanken** [xetdata/nfsserve#25]
Hi, 

Correct me if I am wrong but seems like there's no way to enable case insensitivity in the lib yet. Is there any plan to add that support in the future or any workaround we can do to achieve the purpose?

One workaround I can think of is keep the fs metadata in our own implementation and compare the request and memory with lowercase during lookup() call and return the fileid3. Will that be sufficient or there's things more profound in the lib?

Thanks!

**Comment by ylow** [comment]
Hmm... I don't believe the library inherently assumes case sensitivity or insensitivity. I think you will need to just need to make sure all the file operations that take filename3 (or any other path information) handle the case insensitive case.

**Comment by latot** [comment]
@ylow just as a note and curiosity, some systems has some problems with case sensitivity, like windows who works as non-sensitive one, and there seems to be some problems like https://community.spiceworks.com/t/nfs-case-insenstive/748725.

No idea of the lib could handle something like this, or maybe there can be other things I don't know.
