### ISSUE TITLE
Chromium network access from NFS mount

### ISSUE THREAD

**Issue by freshmanken** [xetdata/nfsserve#26]
Hi,

I am trying to execute a program that uses chromium underneath to access network but it fails. Searched around looks like chromium is not supported to run in the NFS mount due to sandbox mode : https://superuser.com/questions/837229/chromium-browser-will-not-work-when-in-located-on-network-drive. Curious is there a way to bypass this in the NFS serve lib? (Unfortunately I don't have option to configure or avoid chromium right now)

Thanks!

**Comment by ylow** [comment]
Hmmmm... From that issue you linked posted it looks like there is a "--no-sandbox" command you can pass to chromium?

**Comment by freshmanken** [comment]
I am trying to run a program that wraps chromium, I don't have permission to modify that program so I cannot pass that command :(
