### ISSUE TITLE
Confused about first word in readme.md

### ISSUE THREAD

**Issue by willser** [xetdata/nfsserve#5]
Hello team

What is [Ihis](https://github.com/xetdata/nfsserve/blob/bc2a2500b3b0b2f4b3db5d76c7629f160f8552cf/README.md?plain=1#L3)? I search it in bing and github but got nothing like nfs or other similar stuff.Did I miss something?

**Comment by lnicola** [comment]
Typo for "This" :slightly_smiling_face:.

**Comment by willser** [comment]
> Typo for "This" 🙂.

Thanks,I see.
